-- SaaS control plane: never expose these records to tenant users.
create table public.platform_admins (user_id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());
create table public.saas_plans (id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,price_xof numeric(14,2) not null default 0,member_limit integer,features jsonb not null default '[]',active boolean not null default true,created_at timestamptz not null default now());
create table public.saas_subscriptions (id uuid primary key default gen_random_uuid(),organization_id uuid not null unique references public.organizations(id) on delete cascade,plan_id uuid references public.saas_plans(id),status text not null default 'trialing' check(status in('trialing','active','past_due','cancelled')),starts_at timestamptz not null default now(),ends_at timestamptz,updated_at timestamptz not null default now());
create table public.saas_invoices (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,subscription_id uuid references public.saas_subscriptions(id),amount numeric(14,2) not null check(amount>=0),currency char(3) not null default 'XOF',status text not null default 'draft' check(status in('draft','open','paid','void')),due_at date,paid_at timestamptz,created_at timestamptz not null default now());
create or replace function public.is_platform_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.platform_admins where user_id=auth.uid())$$;
alter table public.platform_admins enable row level security;alter table public.saas_plans enable row level security;alter table public.saas_subscriptions enable row level security;alter table public.saas_invoices enable row level security;
create policy "admins read admins" on public.platform_admins for select using(public.is_platform_admin());
create policy "admins manage plans" on public.saas_plans for all using(public.is_platform_admin()) with check(public.is_platform_admin());
create policy "public reads active plans" on public.saas_plans for select to anon, authenticated using(active = true or public.is_platform_admin());
create policy "admins manage subscriptions" on public.saas_subscriptions for all using(public.is_platform_admin()) with check(public.is_platform_admin());
create policy "admins manage invoices" on public.saas_invoices for all using(public.is_platform_admin()) with check(public.is_platform_admin());
-- Bootstrap exactly one trusted account after signup: insert into public.platform_admins(user_id) values ('AUTH_USER_UUID');
