import Link from "next/link";
import { getPublicPlans, planLimits, planPrice } from "@/lib/public-plans";
import "./landing.css";

const organizationTypes = ["Mutuelles", "Tontines", "Associations", "Coopératives", "Syndicats", "ONG", "Partis politiques"];

export default async function Home() {
  const plans = await getPublicPlans();
  return <main className="nayoora-site premium-landing">
    <div className="mesh-gradient-bg"></div>
    <nav className="nayoora-nav glass-nav"><Link href="/" className="brand"><img src="/nayoora-logo.png" alt="Logo NAYOORA" /> NAYOORA</Link><div className="nav-links"><a href="#plateforme">La plateforme</a><a href="#solutions">Vos besoins</a><Link href="/offres">Tarifs</Link><a href="#demarrer">Comment démarrer</a></div><div className="nav-actions"><Link href="/login" className="login-link">Connexion</Link><Link className="button premium-button" href="/offres">Créer mon espace <span>→</span></Link></div></nav>

    <section className="original-hero premium-hero"><div className="hero-editorial"><p className="eyebrow fade-in">Gérez. Connectez. Développez.</p><h1 className="slide-up">Quand votre collectif avance, <br/><em className="text-gradient">tout devient possible.</em></h1><p className="hero-lede slide-up-delay">NAYOORA réunit les personnes, les cotisations, les activités et les décisions dans un espace simple, fluide et élégant.</p><div className="hero-actions fade-in-delay"><Link className="button premium-button" href="/offres">Démarrer maintenant <span>→</span></Link><a className="text-link" href="#plateforme">Explorer la plateforme</a></div><div className="hero-stats fade-in-delay"><div><b className="text-gradient">6</b><span>types d’organisations</span></div><div><b className="text-gradient">1</b><span>espace partagé</span></div><div><b className="text-gradient">∞</b><span>possibilités de grandir</span></div></div></div><div className="hero-community-art float-animation"><img src="/nayoora-hero-community.png" alt="Une équipe africaine pilote son organisation grâce à des outils numériques" /></div></section>

    <section className="organisation-ribbon glass-ribbon"><span>Conçue pour les organisations qui font bouger les lignes</span><div>{organizationTypes.map((label, index) => <b key={label}><i>{["◌", "◍", "✦", "⌁", "↗", "♡", "◇"][index]}</i>{label}</b>)}</div></section>

    <section id="plateforme" className="platform-intro"><div><p className="eyebrow">Une base solide</p><h2>Ce qui compte, enfin à sa place.</h2></div><p>Chaque équipe travaille avec les informations qui lui sont utiles. Les responsables gardent la vue d’ensemble, les membres restent connectés, et vos données appartiennent à votre organisation.</p></section>

    <section className="capability-grid bento-grid"><article className="capability-card glass-card card-members"><span>01</span><div className="capability-icon">◎</div><h3>Une communauté vivante</h3><p>Fiches membres, cartes, rôles, invitations et portail personnel : chacun trouve sa place.</p><a href="#communaute">Gérer les membres <b className="arrow">→</b></a></article><article className="capability-card glass-card card-money"><span>02</span><div className="capability-icon">◒</div><h3>Des finances lisibles</h3><p>Cotisations, caisse, Mobile Money, prêts et états financiers sans perdre le fil.</p><a href="#finances">Piloter les finances <b className="arrow">→</b></a></article><article className="capability-card glass-card card-action"><span>03</span><div className="capability-icon">✦</div><h3>Des actions qui rassemblent</h3><p>Événements, convocations, communications et rapports pour passer de l’idée à l’impact.</p><a href="#communaute">Organiser vos actions <b className="arrow">→</b></a></article></section>

    <section id="solutions" className="solutions-wrapper">
      <div id="finances" className="story-section finance-story"><div className="story-art glass-image-wrapper"><img src="/nayoora-finance-illustration.png" alt="Illustration de la gestion financière et du Mobile Money" /></div><div className="story-copy"><p className="eyebrow">Finances & cotisations</p><h2>Gardez le cap, même quand l’activité s’accélère.</h2><p>Visualisez ce qui entre, ce qui sort et ce qui reste à encaisser. NAYOORA transforme vos données quotidiennes en décisions plus simples.</p><ul className="feature-list"><li>Suivi des cotisations et paiements</li><li>Caisses, comptes et rapprochements</li><li>Rapports prêts à partager</li></ul><Link className="button button-outline premium-outline" href="/offres">Créer mon organisation</Link></div></div>

      <div id="communaute" className="story-section community-story"><div className="story-copy"><p className="eyebrow">Membres, Activités & communication</p><h2>Faites circuler l’information. Faites grandir l’engagement.</h2><p>Un message, une convocation ou une activité ne devrait jamais se perdre entre plusieurs groupes. Rassemblez vos membres, facilitez les échanges et mobilisez au bon moment.</p><div className="story-notes"><span className="glass-pill">Fiches membres & cartes</span><span className="glass-pill">Événements & présences</span><span className="glass-pill">SMS, email & WhatsApp</span></div></div><div className="story-art glass-image-wrapper"><img src="/nayoora-community-illustration.png" alt="Illustration d’une communauté qui organise ses activités" /></div></div>
    </section>

    <section id="tarifs" className="pricing-section"><div className="pricing-heading"><p className="eyebrow">Des offres qui évoluent avec vous</p><h2>Commencez simplement. Grandissez sans changer d’outil.</h2><p>Chaque offre inclut la sécurité multi-organisation, les rôles et permissions, ainsi que l’accompagnement NAYOORA.</p></div><div className="pricing-grid">{plans.map((plan, index) => <article className={`pricing-card ${index === 1 ? "pricing-featured premium-glow" : ""}`} key={plan.id}>{index === 1 && <b className="pricing-badge">Le plus choisi</b>}<p className="plan-name">{plan.name}</p><h3>{planPrice(plan)} <small>FCFA / mois</small></h3><span className="plan-desc">{plan.code === "free" ? "Pour démarrer sereinement" : plan.code === "unlimited" ? "Pour les organisations en mouvement" : "Pour piloter l’activité au quotidien"}</span><ul className="feature-list">{planLimits(plan).map((feature) => <li key={feature}>{feature}</li>)}</ul><Link className={`button ${index === 1 ? "premium-button" : "button-outline premium-outline"}`} href={`/signup?offer=${plan.code}`}>Choisir {plan.name}</Link></article>)}</div></section>

    <section id="demarrer" className="start-section premium-start"><div className="start-bg-glow"></div><p className="eyebrow">Un départ simple</p><h2>Trois étapes pour passer de l’organisation au mouvement.</h2><div className="start-steps premium-steps"><article className="step-card"><b className="step-number">1</b><h3>Créez votre espace</h3><p>Avec votre email ou votre compte Google, en quelques instants.</p></article><article className="step-card"><b className="step-number">2</b><h3>Choisissez votre fonctionnement</h3><p>Type d’organisation, modules et rôles : tout s’adapte à vous.</p></article><article className="step-card"><b className="step-number">3</b><h3>Invitez votre équipe</h3><p>Ajoutez vos membres et commencez à piloter ensemble.</p></article></div></section>

    <section className="trust-cta premium-cta"><div className="cta-content"><p className="eyebrow text-gradient-light">Vos données, vos règles</p><h2>Une plateforme qui respecte la confiance que l’on vous accorde.</h2><p>Isolation par organisation, accès selon les rôles, historique d’activité et sécurité intégrée dès le départ.</p></div><Link className="button premium-button-light" href="/offres">Commencer avec NAYOORA <span>→</span></Link></section>

    <footer className="nayoora-footer premium-footer">
      <Link href="/" className="brand"><img src="/nayoora-logo.png" alt="" /> NAYOORA</Link>
      <span>Gérez. Connectez. Développez.</span>
      <span className="support-phone">Support : +225 07 57 22 87 31</span>
      <span>© {new Date().getFullYear()} NAYOORA</span>
    </footer>
  </main>;
}
