import Link from "next/link";

export default function Home() {
  return <main className="marketing-shell">
    <nav className="marketing-nav"><Link href="/" className="brand"><img src="/nayoora-logo.png" alt="Logo NAYOORA" /> NAYOORA</Link><div><a href="#fonctionnalites">Fonctionnalités</a><a href="#organisations">Solutions</a><Link href="/login">Connexion</Link><Link className="button button-primary" href="/signup">Créer mon espace</Link></div></nav>
    <section className="nayoora-hero"><div className="hero-copy-block"><p className="eyebrow">Gérez. Connectez. Développez.</p><h1>La plateforme de gestion des <em>organisations africaines.</em></h1><p>Centralisez vos membres, cotisations, finances, activités et communications dans un espace simple, sécurisé et adapté au terrain.</p><div className="hero-actions"><Link className="button button-primary" href="/signup">Commencer gratuitement <span>→</span></Link><a className="text-link" href="#fonctionnalites">Découvrir NAYOORA</a></div><div className="hero-proof"><span>✓ Multi-organisation</span><span>✓ Mobile Money prêt</span><span>✓ Données sécurisées</span></div></div><div className="hero-visual"><img src="/nayoora-product-preview.png" alt="Aperçu du tableau de bord NAYOORA sur ordinateur et mobile" /></div></section>
    <section id="organisations" className="organization-types"><p className="eyebrow">Une solution, six réalités</p><h2>Votre organisation a son vocabulaire. NAYOORA s’y adapte.</h2><div>{[["◎","Mutuelles"],["◒","Associations"],["♧","Coopératives"],["↗","Syndicats"],["♥","ONG"],["◆","Partis politiques"]].map(([icon,label])=><article key={label}><b>{icon}</b><span>{label}</span></article>)}</div></section>
    <section id="fonctionnalites" className="feature-section"><div><p className="eyebrow">Tout ce qu’il faut</p><h2>Un pilotage clair, de l’adhésion au rapport.</h2><p>Chaque module est activé selon le type d’organisation et les droits de votre équipe.</p></div><div className="feature-grid"><article><span>◎</span><h3>Membres</h3><p>Fiches, cartes, segments et portail personnel.</p></article><article><span>◌</span><h3>Finances</h3><p>Cotisations, caisse, prêts, créances et rapports.</p></article><article><span>✉</span><h3>Communication</h3><p>Messages internes, email, SMS et WhatsApp.</p></article><article><span>▤</span><h3>Activités</h3><p>Événements, convocations, présences et documents.</p></article></div></section>
    <section className="how-section"><p className="eyebrow">Un démarrage sans friction</p><h2>Votre organisation est prête en trois étapes.</h2><div><article><b>01</b><h3>Créez votre compte</h3><p>Inscrivez-vous avec votre email ou votre compte Google.</p></article><article><b>02</b><h3>Configurez l’organisation</h3><p>Choisissez le type d’organisation et activez les modules utiles.</p></article><article><b>03</b><h3>Pilotez simplement</h3><p>Ajoutez vos membres, encaissez et gardez la vue d’ensemble.</p></article></div></section>
    <section className="security-banner"><div><p className="eyebrow">Confiance & sécurité</p><h2>Vos données restent dans votre organisation.</h2><p>Isolation multi-tenant, rôles, permissions, journal d’activité et politiques de sécurité intégrées.</p></div><Link className="button button-light" href="/signup">Démarrer avec NAYOORA</Link></section>
    <footer className="marketing-footer"><span>© {new Date().getFullYear()} NAYOORA</span><span>Gérez. Connectez. Développez.</span></footer>
  </main>;
}
