import Link from "next/link";

const organizationTypes = ["Mutuelles", "Tontines", "Associations", "Coopératives", "Syndicats", "ONG", "Partis politiques"];

export default function Home() {
  return <main className="nayoora-site">
    <nav className="nayoora-nav"><Link href="/" className="brand"><img src="/nayoora-logo.png" alt="Logo NAYOORA" /> NAYOORA</Link><div className="nav-links"><a href="#plateforme">La plateforme</a><a href="#solutions">Vos besoins</a><Link href="/offres">Tarifs</Link><a href="#demarrer">Comment démarrer</a></div><div className="nav-actions"><Link href="/login">Connexion</Link><Link className="button button-primary" href="/offres">Créer mon espace <span>→</span></Link></div></nav>

    <section className="original-hero"><div className="hero-editorial"><p className="eyebrow">Gérez. Connectez. Développez.</p><h1>Quand votre collectif avance, <em>tout devient possible.</em></h1><p className="hero-lede">NAYOORA réunit les personnes, les cotisations, les activités et les décisions dans un espace simple à prendre en main.</p><div className="hero-actions"><Link className="button button-primary" href="/offres">Démarrer maintenant <span>→</span></Link><a className="text-link" href="#plateforme">Explorer la plateforme</a></div><div className="hero-stats"><div><b>6</b><span>types d’organisations</span></div><div><b>1</b><span>espace partagé</span></div><div><b>∞</b><span>possibilités de grandir</span></div></div></div><div className="hero-community-art"><img src="/nayoora-hero-community.png" alt="Une équipe africaine pilote son organisation grâce à des outils numériques" /></div></section>

    <section className="organisation-ribbon"><span>Conçue pour les organisations qui font bouger les lignes</span><div>{organizationTypes.map((label, index) => <b key={label}><i>{["◌", "◍", "✦", "⌁", "↗", "♡", "◇"][index]}</i>{label}</b>)}</div></section>

    <section id="plateforme" className="platform-intro"><div><p className="eyebrow">Une base solide</p><h2>Ce qui compte, enfin à sa place.</h2></div><p>Chaque équipe travaille avec les informations qui lui sont utiles. Les responsables gardent la vue d’ensemble, les membres restent connectés, et vos données appartiennent à votre organisation.</p></section>

    <section className="capability-grid"><article className="capability-card card-members"><span>01</span><div className="capability-icon">◎</div><h3>Une communauté vivante</h3><p>Fiches membres, cartes, rôles, invitations et portail personnel : chacun trouve sa place.</p><a href="#demarrer">Gérer les membres <b>→</b></a></article><article className="capability-card card-money"><span>02</span><div className="capability-icon">◒</div><h3>Des finances lisibles</h3><p>Cotisations, caisse, Mobile Money, prêts et états financiers sans perdre le fil.</p><a href="#solutions">Piloter les finances <b>→</b></a></article><article className="capability-card card-action"><span>03</span><div className="capability-icon">✦</div><h3>Des actions qui rassemblent</h3><p>Événements, convocations, communications et rapports pour passer de l’idée à l’impact.</p><a href="#solutions">Organiser vos actions <b>→</b></a></article></section>

    <section id="solutions" className="story-section finance-story"><div className="story-art"><img src="/nayoora-finance-illustration.png" alt="Illustration de la gestion financière et du Mobile Money" /></div><div className="story-copy"><p className="eyebrow">Finances & cotisations</p><h2>Gardez le cap, même quand l’activité s’accélère.</h2><p>Visualisez ce qui entre, ce qui sort et ce qui reste à encaisser. NAYOORA transforme vos données quotidiennes en décisions plus simples.</p><ul><li>Suivi des cotisations et paiements</li><li>Caisses, comptes et rapprochements</li><li>Rapports prêts à partager</li></ul><Link className="button button-outline" href="/offres">Créer mon organisation</Link></div></section>

    <section className="story-section community-story"><div className="story-copy"><p className="eyebrow">Activités & communication</p><h2>Faites circuler l’information. Faites grandir l’engagement.</h2><p>Un message, une convocation ou une activité ne devrait jamais se perdre entre plusieurs groupes. Rassemblez vos échanges et mobilisez au bon moment.</p><div className="story-notes"><span>Événements & présences</span><span>SMS, email & WhatsApp</span><span>Documents & rapports</span></div></div><div className="story-art"><img src="/nayoora-community-illustration.png" alt="Illustration d’une communauté qui organise ses activités" /></div></section>

    <section id="tarifs" className="pricing-section"><div className="pricing-heading"><p className="eyebrow">Des offres qui évoluent avec vous</p><h2>Commencez simplement. Grandissez sans changer d’outil.</h2><p>Chaque offre inclut la sécurité multi-organisation, les rôles et permissions, ainsi que l’accompagnement NAYOORA.</p></div><div className="pricing-grid"><article><p>Gratuit</p><h3>0 <small>FCFA / mois</small></h3><span>Pour démarrer sereinement</span><ul><li>Jusqu’à 3 administrateurs</li><li>Jusqu’à 15 membres</li><li>Membres, cotisations & messages</li></ul><Link className="button button-outline" href="/signup?offer=free">Choisir Gratuit</Link></article><article className="pricing-featured"><b className="pricing-badge">Le plus choisi</b><p>Croissance</p><h3>6 500 <small>FCFA / mois</small></h3><span>Pour piloter l’activité au quotidien</span><ul><li>Jusqu’à 5 administrateurs</li><li>Jusqu’à 50 membres</li><li>Finances, événements & rapports</li></ul><Link className="button button-primary" href="/signup?offer=standard">Choisir Croissance</Link></article><article><p>Illimitée</p><h3>12 700 <small>FCFA / mois</small></h3><span>Pour les organisations en mouvement</span><ul><li>Administrateurs illimités</li><li>Membres illimités</li><li>Tous les modules NAYOORA</li></ul><Link className="button button-outline" href="/signup?offer=unlimited">Choisir Illimitée</Link></article></div></section>

    <section id="demarrer" className="start-section"><p className="eyebrow">Un départ simple</p><h2>Trois étapes pour passer de l’organisation au mouvement.</h2><div className="start-steps"><article><b>1</b><h3>Créez votre espace</h3><p>Avec votre email ou votre compte Google, en quelques instants.</p></article><article><b>2</b><h3>Choisissez votre fonctionnement</h3><p>Type d’organisation, modules et rôles : tout s’adapte à vous.</p></article><article><b>3</b><h3>Invitez votre équipe</h3><p>Ajoutez vos membres et commencez à piloter ensemble.</p></article></div></section>

    <section className="trust-cta"><div><p className="eyebrow">Vos données, vos règles</p><h2>Une plateforme qui respecte la confiance que l’on vous accorde.</h2><p>Isolation par organisation, accès selon les rôles, historique d’activité et sécurité intégrée dès le départ.</p></div><Link className="button button-light" href="/offres">Commencer avec NAYOORA <span>→</span></Link></section>

    <footer className="nayoora-footer"><Link href="/" className="brand"><img src="/nayoora-logo.png" alt="" /> NAYOORA</Link><span>Gérez. Connectez. Développez.</span><span>© {new Date().getFullYear()} NAYOORA</span></footer>
  </main>;
}
